#!/usr/bin/env python
"""Upload local JSONL traces (generated by observability.JsonlTracer) to LangSmith.

Usage:
  python scripts/ops/upload_jsonl_traces_to_langsmith.py \
      --trace-dir artifacts/remote_traces \
      --project wind_agent
"""

from __future__ import annotations

import argparse
import json
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from langsmith import Client
from langsmith.run_trees import RunTree


def _dt_from_ms(ms: Any) -> datetime:
    try:
        v = int(ms)
    except Exception:
        v = 0
    return datetime.fromtimestamp(max(0, v) / 1000.0, tz=timezone.utc)


def _load_records(trace_dir: Path) -> tuple[list[dict[str, Any]], int]:
    rows: list[dict[str, Any]] = []
    bad = 0
    for p in sorted(trace_dir.glob("*.jsonl")):
        for i, line in enumerate(p.read_text(encoding="utf-8").splitlines(), start=1):
            t = line.strip()
            if not t:
                continue
            try:
                rec = json.loads(t)
                rec["_source_file"] = str(p)
                rec["_source_line"] = i
                rows.append(rec)
            except Exception:
                bad += 1
    return rows, bad


def _load_uploaded_ids(state_file: Path) -> set[str]:
    if not state_file.exists():
        return set()
    return {x.strip() for x in state_file.read_text(encoding="utf-8").splitlines() if x.strip()}


def _append_uploaded_id(state_file: Path, trace_id: str) -> None:
    state_file.parent.mkdir(parents=True, exist_ok=True)
    with state_file.open("a", encoding="utf-8") as f:
        f.write(trace_id + "\n")


def _record_ts(rec: dict[str, Any]) -> int:
    if rec.get("record_type") == "span":
        try:
            return int(rec.get("started_at_ms") or 0)
        except Exception:
            return 0
    try:
        return int(rec.get("ts_ms") or 0)
    except Exception:
        return 0


def upload(trace_dir: Path, project: str, endpoint: str, api_key: str, state_file: Path, limit: int) -> None:
    rows, bad = _load_records(trace_dir)
    by_trace: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for rec in rows:
        tid = str(rec.get("trace_id") or "").strip()
        if tid:
            by_trace[tid].append(rec)

    uploaded = _load_uploaded_ids(state_file)
    client_kwargs: dict[str, Any] = {"api_key": api_key}
    if endpoint:
        client_kwargs["api_url"] = endpoint
    client = Client(**client_kwargs)

    ok = 0
    skip = 0
    fail = 0
    done = 0

    for trace_id, records in by_trace.items():
        if limit > 0 and done >= limit:
            break
        done += 1
        if trace_id in uploaded:
            skip += 1
            continue
        records.sort(key=_record_ts)
        start_dt = _dt_from_ms(_record_ts(records[0]))
        root = RunTree(
            name="wind_agent_request_offline_relay",
            run_type="chain",
            project_name=project,
            client=client,
            start_time=start_dt,
            inputs={"trace_id": trace_id},
            extra={"metadata": {"trace_id": trace_id, "relay": "jsonl"}},
        )
        try:
            root.post()
            span_cnt = 0
            event_cnt = 0
            for rec in records:
                rt = rec.get("record_type")
                if rt == "span":
                    span_cnt += 1
                    name = str(rec.get("span") or "span")
                    sdt = _dt_from_ms(rec.get("started_at_ms"))
                    edt = _dt_from_ms(rec.get("ended_at_ms"))
                    child = root.create_child(
                        name=name,
                        run_type="chain",
                        start_time=sdt,
                        inputs={"trace_id": trace_id},
                        extra={"metadata": rec.get("metadata") or {}},
                    )
                    child.post()
                    err = str(rec.get("error") or "").strip() or None
                    child.end(
                        outputs={
                            "status": rec.get("status", "ok"),
                            "duration_ms": rec.get("duration_ms"),
                            "metadata": rec.get("metadata") or {},
                            "source": {"file": rec.get("_source_file"), "line": rec.get("_source_line")},
                        },
                        error=err,
                        end_time=edt,
                    )
                    child.patch()
                elif rt == "event":
                    event_cnt += 1
                    name = f"event:{str(rec.get('event') or 'event')}"
                    edt = _dt_from_ms(rec.get("ts_ms"))
                    child = root.create_child(
                        name=name,
                        run_type="tool",
                        start_time=edt,
                        inputs={"trace_id": trace_id},
                        extra={"metadata": rec.get("metadata") or {}},
                    )
                    child.post()
                    child.end(
                        outputs={
                            "event": rec.get("event"),
                            "metadata": rec.get("metadata") or {},
                            "source": {"file": rec.get("_source_file"), "line": rec.get("_source_line")},
                        },
                        end_time=edt,
                    )
                    child.patch()
            root.end(
                outputs={
                    "status": "ok",
                    "trace_id": trace_id,
                    "span_count": span_cnt,
                    "event_count": event_cnt,
                    "record_count": len(records),
                },
                end_time=_dt_from_ms(_record_ts(records[-1])),
            )
            root.patch()
            _append_uploaded_id(state_file, trace_id)
            ok += 1
        except Exception as exc:
            fail += 1
            try:
                root.end(outputs={"status": "error", "trace_id": trace_id}, error=str(exc))
                root.patch()
            except Exception:
                pass

    print(
        json.dumps(
            {
                "trace_dir": str(trace_dir),
                "project": project,
                "endpoint": endpoint or "default",
                "total_records": len(rows),
                "bad_lines": bad,
                "trace_groups": len(by_trace),
                "uploaded": ok,
                "skipped_already_uploaded": skip,
                "failed": fail,
                "state_file": str(state_file),
            },
            ensure_ascii=False,
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Upload JSONL traces to LangSmith")
    parser.add_argument("--trace-dir", default="artifacts/remote_traces")
    parser.add_argument("--project", default="wind_agent")
    parser.add_argument("--endpoint", default="")
    parser.add_argument("--api-key", default="")
    parser.add_argument("--state-file", default="artifacts/remote_traces/.uploaded_trace_ids.txt")
    parser.add_argument("--limit", type=int, default=0, help="Max trace groups to upload, 0 means no limit")
    args = parser.parse_args()

    trace_dir = Path(args.trace_dir).resolve()
    if not trace_dir.exists():
        raise SystemExit(f"trace dir not found: {trace_dir}")
    api_key = str(args.api_key or "").strip()
    if not api_key:
        raise SystemExit("missing api key: set --api-key or LANGSMITH_API_KEY")
    endpoint = str(args.endpoint or "").strip()
    if not endpoint:
        endpoint = str(__import__("os").getenv("LANGSMITH_ENDPOINT", "")).strip()
    project = str(args.project or "").strip() or "wind_agent"
    upload(
        trace_dir=trace_dir,
        project=project,
        endpoint=endpoint,
        api_key=api_key,
        state_file=Path(args.state_file).resolve(),
        limit=int(args.limit or 0),
    )


if __name__ == "__main__":
    main()

